# Generated by Django 3.1.13 on 2023-03-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_all_client_trips_tinder_review_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='days',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Количество дней'),
        ),
    ]
