# Generated by Django 4.1.7 on 2023-03-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_all_client_trips_id_alter_preferences_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourshots',
            old_name='movie',
            new_name='tour',
        ),
    ]
